name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # 添加调试信息
    - name: Debug directory structure
      run: |
        ls -la
        ls -la gradle/wrapper
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    # 确保在正确目录执行
    - name: Build with Gradle
      run: |
        pwd
        ./gradlew assembleDebug --stacktrace
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: app/build/outputs/apk/**/*.apk
